import {
  Employee,
  WorkingSchedule,
  SalaryStructure,
  SalaryRule,
  Payrun,
} from "@/types/hr";

// ─── Working Schedules ────────────────────────────────────────────────────────
export const initialSchedules: WorkingSchedule[] = [
  { id: 1, name: "Standard 40h", schedule_type: "FIXED", weekly_hours: 40 },
  { id: 2, name: "Flexible 38h", schedule_type: "FLEXIBLE", weekly_hours: 38 },
  { id: 3, name: "Part-Time 20h", schedule_type: "PART_TIME", weekly_hours: 20 },
];

// ─── Employees with nested relations ─────────────────────────────────────────
export const initialEmployees: Employee[] = [
  {
    id: 1,
    first_name: "Priya",
    last_name: "Sharma",
    email: "priya.sharma@company.com",
    phone: "+91 98765 43210",
    department: "Product Design",
    job_position: "Lead UI Designer",
    manager_id: null,
    manager_name: null,
    schedule_id: 1,
    schedule_name: "Standard 40h",
    status: "ACTIVE",
    bank_account_no: "HDFC0041234567",
    bank_name: "HDFC Bank",
    ifsc_code: "HDFC0001234",
    tax_id: "ABCPS1234D",
    joining_date: "2022-03-15",
    avatar_url: "https://images.unsplash.com/photo-1494790108755-2616b612b786?auto=format&fit=crop&w=100&q=80",
    contracts: [
      {
        id: 101,
        name: "Priya Sharma / Standard 2026",
        employee_id: 1,
        start_date: "2026-01-01",
        end_date: null,
        wage: 75000,
        salary_structure_id: 1,
        salary_structure_name: "India Standard Payroll",
        status: "ACTIVE",
      },
    ],
    attendances: [
      {
        id: 1001,
        employee_id: 1,
        date: "2026-09-01",
        check_in: "09:00",
        check_out: "18:00",
        worked_hours: 9,
        overtime_hours: 1,
        status: "OVERTIME",
        notes: null,
      },
      {
        id: 1002,
        employee_id: 1,
        date: "2026-09-02",
        check_in: "09:15",
        check_out: "18:05",
        worked_hours: 8.8,
        overtime_hours: 0,
        status: "LATE",
        notes: "Minor late arrival",
      },
    ],
    leave_allocations: [
      {
        id: 201,
        employee_id: 1,
        time_off_type_id: 1,
        time_off_type_name: "Annual Leave",
        time_off_code: "VACATION",
        allocated_days: 21,
        taken_days: 5,
        year: 2026,
      },
      {
        id: 202,
        employee_id: 1,
        time_off_type_id: 2,
        time_off_type_name: "Sick Leave",
        time_off_code: "SICK",
        allocated_days: 10,
        taken_days: 1,
        year: 2026,
      },
    ],
    leave_requests: [
      {
        id: 301,
        employee_id: 1,
        time_off_type_id: 1,
        time_off_type_name: "Annual Leave",
        time_off_code: "VACATION",
        start_date: "2026-10-15",
        end_date: "2026-10-17",
        days: 3,
        reason: "Family holiday",
        status: "PENDING",
      },
    ],
    payslips: [
      {
        id: 401,
        payrun_id: 1,
        payrun_name: "September 2026 Payrun",
        period_start: "2026-09-01",
        period_end: "2026-09-30",
        basic_wage: 75000,
        gross_wage: 78500,
        total_deductions: 6300,
        net_wage: 72200,
        status: "VALIDATED",
      },
    ],
  },

  {
    id: 2,
    first_name: "Marcus",
    last_name: "Johnson",
    email: "marcus.johnson@company.com",
    phone: "+91 87654 32109",
    department: "Engineering",
    job_position: "Backend Engineer",
    manager_id: null,
    manager_name: null,
    schedule_id: 2,
    schedule_name: "Flexible 38h",
    status: "ACTIVE",
    bank_account_no: "ICIC0078901234",
    bank_name: "ICICI Bank",
    ifsc_code: "ICIC0007890",
    tax_id: "BCPMJ5678E",
    joining_date: "2023-06-01",
    avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=100&q=80",
    contracts: [
      {
        id: 102,
        name: "Marcus Johnson / Engineer 2026",
        employee_id: 2,
        start_date: "2026-01-01",
        end_date: null,
        wage: 85000,
        salary_structure_id: 1,
        salary_structure_name: "India Standard Payroll",
        status: "ACTIVE",
      },
    ],
    attendances: [
      {
        id: 1003,
        employee_id: 2,
        date: "2026-09-01",
        check_in: "09:30",
        check_out: "18:30",
        worked_hours: 9,
        overtime_hours: 1,
        status: "OVERTIME",
        notes: null,
      },
    ],
    leave_allocations: [
      {
        id: 203,
        employee_id: 2,
        time_off_type_id: 1,
        time_off_type_name: "Annual Leave",
        time_off_code: "VACATION",
        allocated_days: 21,
        taken_days: 2,
        year: 2026,
      },
    ],
    leave_requests: [],
    payslips: [
      {
        id: 402,
        payrun_id: 1,
        payrun_name: "September 2026 Payrun",
        period_start: "2026-09-01",
        period_end: "2026-09-30",
        basic_wage: 85000,
        gross_wage: 88200,
        total_deductions: 7400,
        net_wage: 80800,
        status: "VALIDATED",
      },
    ],
  },

  {
    id: 3,
    first_name: "Aarav",
    last_name: "Mehta",
    email: "aarav.mehta@company.com",
    phone: "+91 76543 21098",
    department: "Platform Engineering",
    job_position: "Platform Engineer",
    manager_id: null,
    manager_name: null,
    schedule_id: 1,
    schedule_name: "Standard 40h",
    status: "ACTIVE",
    bank_account_no: "SBI0034567890",
    bank_name: "State Bank of India",
    ifsc_code: "SBIN0003456",
    tax_id: "CDPAM9012F",
    joining_date: "2024-01-10",
    avatar_url: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=100&q=80",
    contracts: [
      {
        id: 103,
        name: "Aarav Mehta / Platform 2026",
        employee_id: 3,
        start_date: "2026-01-01",
        end_date: null,
        wage: 60000,
        salary_structure_id: 1,
        salary_structure_name: "India Standard Payroll",
        status: "ACTIVE",
      },
    ],
    attendances: [
      {
        id: 1004,
        employee_id: 3,
        date: "2026-09-01",
        check_in: "09:05",
        check_out: "20:00",
        worked_hours: 10.9,
        overtime_hours: 2.9,
        status: "OVERTIME",
        notes: "Sprint crunch week",
      },
      {
        id: 1005,
        employee_id: 3,
        date: "2026-09-02",
        check_in: "09:00",
        check_out: "18:00",
        worked_hours: 9,
        overtime_hours: 1,
        status: "OVERTIME",
        notes: null,
      },
    ],
    leave_allocations: [
      {
        id: 204,
        employee_id: 3,
        time_off_type_id: 1,
        time_off_type_name: "Annual Leave",
        time_off_code: "VACATION",
        allocated_days: 21,
        taken_days: 3,
        year: 2026,
      },
      {
        id: 205,
        employee_id: 3,
        time_off_type_id: 3,
        time_off_type_name: "Unpaid Leave",
        time_off_code: "UNPAID",
        allocated_days: 5,
        taken_days: 1,
        year: 2026,
      },
    ],
    leave_requests: [
      {
        id: 302,
        employee_id: 3,
        time_off_type_id: 3,
        time_off_type_name: "Unpaid Leave",
        time_off_code: "UNPAID",
        start_date: "2026-09-15",
        end_date: "2026-09-15",
        days: 1,
        reason: "Personal errand",
        status: "APPROVED",
      },
    ],
    payslips: [
      {
        id: 403,
        payrun_id: 1,
        payrun_name: "September 2026 Payrun",
        period_start: "2026-09-01",
        period_end: "2026-09-30",
        basic_wage: 60000,
        gross_wage: 64200,
        total_deductions: 6700,
        net_wage: 57500,
        status: "COMPUTED",
        warnings: ["1 unpaid day deducted"],
      },
    ],
  },

  {
    id: 4,
    first_name: "Fatima",
    last_name: "Al-Hassan",
    email: "fatima.alhassan@company.com",
    phone: "+91 65432 10987",
    department: "HR Operations",
    job_position: "HR Business Partner",
    manager_id: null,
    manager_name: null,
    schedule_id: 1,
    schedule_name: "Standard 40h",
    status: "ON_LEAVE",
    bank_account_no: "AXIS0056789012",
    bank_name: "Axis Bank",
    ifsc_code: "UTIB0005678",
    tax_id: "EFPFA3456G",
    joining_date: "2021-11-20",
    avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=100&q=80",
    contracts: [
      {
        id: 104,
        name: "Fatima Al-Hassan / HR 2026",
        employee_id: 4,
        start_date: "2026-01-01",
        end_date: null,
        wage: 70000,
        salary_structure_id: 1,
        salary_structure_name: "India Standard Payroll",
        status: "ACTIVE",
      },
    ],
    attendances: [
      {
        id: 1006,
        employee_id: 4,
        date: "2026-08-30",
        check_in: "09:00",
        check_out: "18:00",
        worked_hours: 9,
        overtime_hours: 1,
        status: "NORMAL",
        notes: null,
      },
    ],
    leave_allocations: [
      {
        id: 206,
        employee_id: 4,
        time_off_type_id: 2,
        time_off_type_name: "Sick Leave",
        time_off_code: "SICK",
        allocated_days: 10,
        taken_days: 4,
        year: 2026,
      },
    ],
    leave_requests: [
      {
        id: 303,
        employee_id: 4,
        time_off_type_id: 2,
        time_off_type_name: "Sick Leave",
        time_off_code: "SICK",
        start_date: "2026-09-05",
        end_date: "2026-09-08",
        days: 4,
        reason: "Medical procedure",
        status: "APPROVED",
      },
    ],
    payslips: [
      {
        id: 404,
        payrun_id: 1,
        payrun_name: "September 2026 Payrun",
        period_start: "2026-09-01",
        period_end: "2026-09-30",
        basic_wage: 70000,
        gross_wage: 70000,
        total_deductions: 5600,
        net_wage: 64400,
        status: "DRAFT",
      },
    ],
  },

  {
    id: 5,
    first_name: "Lucas",
    last_name: "Ortega",
    email: "lucas.ortega@company.com",
    phone: "+91 54321 09876",
    department: "Infrastructure",
    job_position: "DevOps Engineer",
    manager_id: null,
    manager_name: null,
    schedule_id: 1,
    schedule_name: "Standard 40h",
    status: "ACTIVE",
    bank_account_no: null,
    bank_name: null,
    ifsc_code: null,
    tax_id: null,
    joining_date: "2025-07-01",
    avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=100&q=80",
    contracts: [
      {
        id: 105,
        name: "Lucas Ortega / DevOps 2026",
        employee_id: 5,
        start_date: "2025-07-01",
        end_date: null,
        wage: 55000,
        salary_structure_id: 1,
        salary_structure_name: "India Standard Payroll",
        status: "ACTIVE",
      },
    ],
    attendances: [
      {
        id: 1007,
        employee_id: 5,
        date: "2026-09-01",
        check_in: "09:00",
        check_out: "17:30",
        worked_hours: 8.5,
        overtime_hours: 0.5,
        status: "OVERTIME",
        notes: null,
      },
    ],
    leave_allocations: [
      {
        id: 207,
        employee_id: 5,
        time_off_type_id: 1,
        time_off_type_name: "Annual Leave",
        time_off_code: "VACATION",
        allocated_days: 12,
        taken_days: 0,
        year: 2026,
      },
    ],
    leave_requests: [],
    payslips: [
      {
        id: 405,
        payrun_id: 1,
        payrun_name: "September 2026 Payrun",
        period_start: "2026-09-01",
        period_end: "2026-09-30",
        basic_wage: 55000,
        gross_wage: 55900,
        total_deductions: 4500,
        net_wage: 51400,
        status: "DRAFT",
        warnings: ["Missing bank account", "Missing Tax ID — payrun blocked"],
      },
    ],
  },
];

// ─── Salary Structures with Ordered Rules (Row 2 & 3) ─────────────────────────
export const initialSalaryStructures: SalaryStructure[] = [
  {
    id: 1,
    name: "Standard Corporate Executive 2026",
    code: "CORP_EXEC_2026",
    description: "Standard statutory salary structure for executive and full-time permanent corporate personnel.",
    is_active: true,
    assigned_contracts_count: 84,
    created_at: "2026-01-10T09:00:00Z",
    updated_at: "2026-08-20T14:30:00Z",
    rules: [
      {
        id: 1,
        structure_id: 1,
        name: "Basic Salary",
        code: "BASIC",
        category: "BASIC",
        sequence: 10,
        computation_type: "PYTHON_EXPRESSION",
        formula: "contract.wage * 0.50",
        is_active: true,
        description: "Statutory 50% base wage component for compliance.",
      },
      {
        id: 2,
        structure_id: 1,
        name: "House Rent Allowance",
        code: "HRA",
        category: "ALLOWANCE",
        sequence: 20,
        computation_type: "PYTHON_EXPRESSION",
        formula: "contract.wage * 0.20",
        is_active: true,
        description: "20% accommodation allowance per Metro classification.",
      },
      {
        id: 3,
        structure_id: 1,
        name: "Dearness Allowance",
        code: "DA",
        category: "ALLOWANCE",
        sequence: 30,
        computation_type: "PYTHON_EXPRESSION",
        formula: "contract.wage * 0.10",
        is_active: true,
        description: "10% cost-of-living adjustment allowance.",
      },
      {
        id: 4,
        structure_id: 1,
        name: "Overtime Pay",
        code: "OT_PAY",
        category: "ALLOWANCE",
        sequence: 35,
        computation_type: "OVERTIME",
        fixed_amount: 1.5,
        is_active: true,
        description: "1.5x hourly rate multiplier for recorded overtime hours beyond 8h/day.",
      },
      {
        id: 5,
        structure_id: 1,
        name: "Gross Wage",
        code: "GROSS",
        category: "GROSS",
        sequence: 40,
        computation_type: "PYTHON_EXPRESSION",
        formula: "BASIC + HRA + DA + OT_PAY",
        is_active: true,
        description: "Cumulative gross period earnings prior to deductions.",
      },
      {
        id: 6,
        structure_id: 1,
        name: "Provident Fund (EPFO)",
        code: "PF",
        category: "DEDUCTION",
        sequence: 50,
        computation_type: "PYTHON_EXPRESSION",
        formula: "BASIC * 0.12",
        is_active: true,
        description: "12% statutory employee contribution towards EPFO.",
      },
      {
        id: 7,
        structure_id: 1,
        name: "Unpaid Leave Deduction",
        code: "LEAVE_DED",
        category: "DEDUCTION",
        sequence: 55,
        computation_type: "LEAVE_DEDUCTION",
        is_active: true,
        description: "Per-day rate deduction for unauthorized or approved unpaid leaves.",
      },
      {
        id: 8,
        structure_id: 1,
        name: "Net Wage Disbursable",
        code: "NET",
        category: "NET",
        sequence: 100,
        computation_type: "PYTHON_EXPRESSION",
        formula: "GROSS - PF - LEAVE_DED",
        is_active: true,
        description: "Final take-home amount wired via direct bank disbursement.",
      },
    ],
  },
  {
    id: 2,
    name: "Tech & Engineering Specialist 2026",
    code: "TECH_ENG_2026",
    description: "Tailored structure for software architects, data engineers, and cloud infrastructure specialists.",
    is_active: true,
    assigned_contracts_count: 42,
    created_at: "2026-02-01T11:15:00Z",
    updated_at: "2026-09-01T10:00:00Z",
    rules: [
      {
        id: 9,
        structure_id: 2,
        name: "Basic Salary",
        code: "BASIC",
        category: "BASIC",
        sequence: 10,
        computation_type: "PYTHON_EXPRESSION",
        formula: "contract.wage * 0.45",
        is_active: true,
        description: "45% core base wage.",
      },
      {
        id: 10,
        structure_id: 2,
        name: "Special Tech Allowance",
        code: "TECH_ALLOW",
        category: "ALLOWANCE",
        sequence: 20,
        computation_type: "FIXED",
        fixed_amount: 15000,
        is_active: true,
        description: "Fixed monthly tech stipend for continuous learning and tools.",
      },
      {
        id: 11,
        structure_id: 2,
        name: "Flexible Benefit Allowance",
        code: "FBA",
        category: "ALLOWANCE",
        sequence: 25,
        computation_type: "PYTHON_EXPRESSION",
        formula: "contract.wage * 0.25",
        is_active: true,
        description: "25% flexible bucket for wellness, books, and internet.",
      },
      {
        id: 12,
        structure_id: 2,
        name: "Weekend Incident OT",
        code: "OT_PAY",
        category: "ALLOWANCE",
        sequence: 35,
        computation_type: "OVERTIME",
        fixed_amount: 2.0,
        is_active: true,
        description: "2.0x double-rate multiplier for high-severity weekend on-call incident response.",
      },
      {
        id: 13,
        structure_id: 2,
        name: "Gross Wage",
        code: "GROSS",
        category: "GROSS",
        sequence: 40,
        computation_type: "PYTHON_EXPRESSION",
        formula: "BASIC + TECH_ALLOW + FBA + OT_PAY",
        is_active: true,
        description: "Total monthly gross compensation.",
      },
      {
        id: 14,
        structure_id: 2,
        name: "Provident Fund",
        code: "PF",
        category: "DEDUCTION",
        sequence: 50,
        computation_type: "PYTHON_EXPRESSION",
        formula: "BASIC * 0.12",
        is_active: true,
        description: "12% statutory PF deduction on base wage.",
      },
      {
        id: 15,
        structure_id: 2,
        name: "Professional Tax",
        code: "PROF_TAX",
        category: "DEDUCTION",
        sequence: 52,
        computation_type: "FIXED",
        fixed_amount: 200,
        is_active: true,
        description: "State professional tax slab deduction.",
      },
      {
        id: 16,
        structure_id: 2,
        name: "Net Wage Disbursable",
        code: "NET",
        category: "NET",
        sequence: 100,
        computation_type: "PYTHON_EXPRESSION",
        formula: "GROSS - PF - PROF_TAX",
        is_active: true,
        description: "Final net wage payable.",
      },
    ],
  },
  {
    id: 3,
    name: "Commercial & Sales Commission 2026",
    code: "SALES_COMM_2026",
    description: "Revenue-linked salary structure with target performance bonuses and statutory protections.",
    is_active: true,
    assigned_contracts_count: 18,
    created_at: "2026-03-15T08:30:00Z",
    updated_at: "2026-07-12T16:45:00Z",
    rules: [
      {
        id: 17,
        structure_id: 3,
        name: "Base Retainer Salary",
        code: "BASIC",
        category: "BASIC",
        sequence: 10,
        computation_type: "PYTHON_EXPRESSION",
        formula: "contract.wage * 0.40",
        is_active: true,
        description: "40% guaranteed retainer base.",
      },
      {
        id: 18,
        structure_id: 3,
        name: "House Rent Allowance",
        code: "HRA",
        category: "ALLOWANCE",
        sequence: 20,
        computation_type: "PYTHON_EXPRESSION",
        formula: "contract.wage * 0.20",
        is_active: true,
        description: "20% housing assistance.",
      },
      {
        id: 19,
        structure_id: 3,
        name: "Target Sales Commission",
        code: "COMMISSION",
        category: "ALLOWANCE",
        sequence: 30,
        computation_type: "PERCENTAGE",
        percentage_value: 15,
        is_active: true,
        description: "15% monthly target quota attainment incentive.",
      },
      {
        id: 20,
        structure_id: 3,
        name: "Gross Wage",
        code: "GROSS",
        category: "GROSS",
        sequence: 40,
        computation_type: "PYTHON_EXPRESSION",
        formula: "BASIC + HRA + COMMISSION",
        is_active: true,
        description: "Total gross sales compensation.",
      },
      {
        id: 21,
        structure_id: 3,
        name: "Provident Fund",
        code: "PF",
        category: "DEDUCTION",
        sequence: 50,
        computation_type: "PYTHON_EXPRESSION",
        formula: "BASIC * 0.12",
        is_active: true,
        description: "12% statutory PF on base retainer.",
      },
      {
        id: 22,
        structure_id: 3,
        name: "Net Wage Disbursable",
        code: "NET",
        category: "NET",
        sequence: 100,
        computation_type: "PYTHON_EXPRESSION",
        formula: "GROSS - PF",
        is_active: true,
        description: "Disbursable sales earnings.",
      },
    ],
  },
];

// ─── Flattened Salary Rules (Row 3) ──────────────────────────────────────────
export const initialSalaryRules: SalaryRule[] = initialSalaryStructures.flatMap(
  (s) => s.rules || []
);

// ─── Payrun Cycles (Rows 4, 5, 6) ───────────────────────────────────────────
export const initialPayruns: Payrun[] = [
  {
    id: 1,
    name: "September 2026 Regular Payrun",
    period_start: "2026-09-01",
    period_end: "2026-09-30",
    salary_structure_id: 1,
    salary_structure_name: "Standard Corporate Executive 2026",
    status: "PAID",
    total_gross: 310900,
    total_deductions: 27950,
    total_net: 282950,
    employee_count: 5,
    warnings_count: 0,
    blocking_errors_count: 0,
    created_at: "2026-09-25T10:00:00Z",
    payslips: [
      {
        id: 401,
        payrun_id: 1,
        payrun_name: "September 2026 Regular Payrun",
        employee_id: 1,
        employee_name: "Priya Sharma",
        employee_avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b786?auto=format&fit=crop&w=100&q=80",
        employee_department: "Product Design",
        employee_job: "Lead UI Designer",
        contract_id: 101,
        contract_wage: 75000,
        period_start: "2026-09-01",
        period_end: "2026-09-30",
        worked_days: 22,
        total_hours: 176,
        overtime_hours: 2,
        unpaid_leave_days: 0,
        basic_wage: 37500,
        gross_wage: 76406.25,
        total_deductions: 4500,
        net_wage: 71906.25,
        status: "PAID",
        warnings: [],
        lines: [
          { id: 1, payslip_id: 401, rule_code: "BASIC", rule_name: "Basic Salary", category: "BASIC", sequence: 10, rate: 100, amount: 37500, calculation_trace: "75000 * 0.50" },
          { id: 2, payslip_id: 401, rule_code: "HRA", rule_name: "House Rent Allowance", category: "ALLOWANCE", sequence: 20, rate: 100, amount: 15000, calculation_trace: "75000 * 0.20" },
          { id: 3, payslip_id: 401, rule_code: "DA", rule_name: "Dearness Allowance", category: "ALLOWANCE", sequence: 30, rate: 100, amount: 7500, calculation_trace: "75000 * 0.10" },
          { id: 4, payslip_id: 401, rule_code: "OT_PAY", rule_name: "Overtime Pay", category: "ALLOWANCE", sequence: 35, rate: 100, amount: 1406.25, calculation_trace: "2h * (75000/160) * 1.5" },
          { id: 5, payslip_id: 401, rule_code: "GROSS", rule_name: "Gross Wage", category: "GROSS", sequence: 40, rate: 100, amount: 76406.25, calculation_trace: "37500 + 15000 + 7500 + 1406.25" },
          { id: 6, payslip_id: 401, rule_code: "PF", rule_name: "Provident Fund", category: "DEDUCTION", sequence: 50, rate: 100, amount: 4500, calculation_trace: "37500 * 0.12" },
          { id: 7, payslip_id: 401, rule_code: "NET", rule_name: "Net Wage", category: "NET", sequence: 100, rate: 100, amount: 71906.25, calculation_trace: "76406.25 - 4500" },
        ],
      },
      {
        id: 402,
        payrun_id: 1,
        payrun_name: "September 2026 Regular Payrun",
        employee_id: 2,
        employee_name: "Devon Vance",
        employee_avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=100&q=80",
        employee_department: "Engineering",
        employee_job: "Senior Backend Engineer",
        contract_id: 102,
        contract_wage: 85000,
        period_start: "2026-09-01",
        period_end: "2026-09-30",
        worked_days: 22,
        total_hours: 176,
        overtime_hours: 4,
        unpaid_leave_days: 0,
        basic_wage: 42500,
        gross_wage: 88187.50,
        total_deductions: 5100,
        net_wage: 83087.50,
        status: "PAID",
        warnings: [],
      },
      {
        id: 403,
        payrun_id: 1,
        payrun_name: "September 2026 Regular Payrun",
        employee_id: 3,
        employee_name: "Aarav Mehta",
        employee_avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=100&q=80",
        employee_department: "Engineering",
        employee_job: "Platform Engineer (EMP-101)",
        contract_id: 103,
        contract_wage: 65000,
        period_start: "2026-09-01",
        period_end: "2026-09-30",
        worked_days: 22,
        total_hours: 176,
        overtime_hours: 0,
        unpaid_leave_days: 0,
        basic_wage: 32500,
        gross_wage: 65000,
        total_deductions: 3900,
        net_wage: 61100,
        status: "PAID",
        warnings: [],
      },
      {
        id: 404,
        payrun_id: 1,
        payrun_name: "September 2026 Regular Payrun",
        employee_id: 4,
        employee_name: "Siddharth Rao",
        employee_avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=100&q=80",
        employee_department: "Product Management",
        employee_job: "Product Manager",
        contract_id: 104,
        contract_wage: 70000,
        period_start: "2026-09-01",
        period_end: "2026-09-30",
        worked_days: 22,
        total_hours: 176,
        overtime_hours: 0,
        unpaid_leave_days: 0,
        basic_wage: 35000,
        gross_wage: 70000,
        total_deductions: 4200,
        net_wage: 65800,
        status: "PAID",
        warnings: [],
      },
      {
        id: 405,
        payrun_id: 1,
        payrun_name: "September 2026 Regular Payrun",
        employee_id: 5,
        employee_name: "Lucas Ortega",
        employee_avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=100&q=80",
        employee_department: "Infrastructure",
        employee_job: "DevOps Engineer",
        contract_id: 105,
        contract_wage: 55000,
        period_start: "2026-09-01",
        period_end: "2026-09-30",
        worked_days: 22,
        total_hours: 176,
        overtime_hours: 1,
        unpaid_leave_days: 0,
        basic_wage: 27500,
        gross_wage: 55515.63,
        total_deductions: 3300,
        net_wage: 52215.63,
        status: "PAID",
        warnings: [],
      },
    ],
  },
  {
    id: 2,
    name: "October 2026 Regular Payrun",
    period_start: "2026-10-01",
    period_end: "2026-10-31",
    salary_structure_id: 1,
    salary_structure_name: "Standard Corporate Executive 2026",
    status: "VALIDATED",
    total_gross: 352400,
    total_deductions: 28950,
    total_net: 323450,
    employee_count: 5,
    warnings_count: 1,
    blocking_errors_count: 0,
    created_at: "2026-10-24T14:30:00Z",
    payslips: [
      {
        id: 406,
        payrun_id: 2,
        payrun_name: "October 2026 Regular Payrun",
        employee_id: 1,
        employee_name: "Priya Sharma",
        employee_avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b786?auto=format&fit=crop&w=100&q=80",
        employee_department: "Product Design",
        employee_job: "Lead UI Designer",
        contract_id: 101,
        contract_wage: 75000,
        period_start: "2026-10-01",
        period_end: "2026-10-31",
        worked_days: 21,
        total_hours: 168,
        overtime_hours: 0,
        unpaid_leave_days: 1,
        basic_wage: 37500,
        gross_wage: 75000,
        total_deductions: 7384.62,
        net_wage: 67615.38,
        status: "VALIDATED",
        warnings: ["1 day unpaid leave deduction applied (-₹2,884.62)"],
      },
    ],
  },
  {
    id: 3,
    name: "November 2026 Preliminary Payrun",
    period_start: "2026-11-01",
    period_end: "2026-11-30",
    salary_structure_id: 1,
    salary_structure_name: "Standard Corporate Executive 2026",
    status: "DRAFT",
    total_gross: 350000,
    total_deductions: 28000,
    total_net: 322000,
    employee_count: 5,
    warnings_count: 2,
    blocking_errors_count: 1,
    created_at: "2026-11-02T09:15:00Z",
    payslips: [],
  },
];

export default initialEmployees;
