import {
  Employee,
  WorkingSchedule,
} from "@/types/hr";

// ─── Working Schedules ────────────────────────────────────────────────────────
export const initialSchedules: WorkingSchedule[] = [
  { id: 1, name: "Standard 40h", schedule_type: "FIXED", weekly_hours: 40 },
  { id: 2, name: "Flexible 38h", schedule_type: "FLEXIBLE", weekly_hours: 38 },
  { id: 3, name: "Part-Time 20h", schedule_type: "PART_TIME", weekly_hours: 20 },
];

// ─── Employees with nested relations ─────────────────────────────────────────
export const initialEmployees: Employee[] = [
  {
    id: 1,
    first_name: "Priya",
    last_name: "Sharma",
    email: "priya.sharma@company.com",
    phone: "+91 98765 43210",
    department: "Product Design",
    job_position: "Lead UI Designer",
    manager_id: null,
    manager_name: null,
    schedule_id: 1,
    schedule_name: "Standard 40h",
    status: "ACTIVE",
    bank_account_no: "HDFC0041234567",
    bank_name: "HDFC Bank",
    ifsc_code: "HDFC0001234",
    tax_id: "ABCPS1234D",
    joining_date: "2022-03-15",
    avatar_url: "https://images.unsplash.com/photo-1494790108755-2616b612b786?auto=format&fit=crop&w=100&q=80",
    contracts: [
      {
        id: 101,
        name: "Priya Sharma / Standard 2026",
        employee_id: 1,
        start_date: "2026-01-01",
        end_date: null,
        wage: 75000,
        salary_structure_id: 1,
        salary_structure_name: "India Standard Payroll",
        status: "ACTIVE",
      },
    ],
    attendances: [
      {
        id: 1001,
        employee_id: 1,
        date: "2026-09-01",
        check_in: "09:00",
        check_out: "18:00",
        worked_hours: 9,
        overtime_hours: 1,
        status: "OVERTIME",
        notes: null,
      },
      {
        id: 1002,
        employee_id: 1,
        date: "2026-09-02",
        check_in: "09:15",
        check_out: "18:05",
        worked_hours: 8.8,
        overtime_hours: 0,
        status: "LATE",
        notes: "Minor late arrival",
      },
    ],
    leave_allocations: [
      {
        id: 201,
        employee_id: 1,
        time_off_type_id: 1,
        time_off_type_name: "Annual Leave",
        time_off_code: "VACATION",
        allocated_days: 21,
        taken_days: 5,
        year: 2026,
      },
      {
        id: 202,
        employee_id: 1,
        time_off_type_id: 2,
        time_off_type_name: "Sick Leave",
        time_off_code: "SICK",
        allocated_days: 10,
        taken_days: 1,
        year: 2026,
      },
    ],
    leave_requests: [
      {
        id: 301,
        employee_id: 1,
        time_off_type_id: 1,
        time_off_type_name: "Annual Leave",
        time_off_code: "VACATION",
        start_date: "2026-10-15",
        end_date: "2026-10-17",
        days: 3,
        reason: "Family holiday",
        status: "PENDING",
      },
    ],
    payslips: [
      {
        id: 401,
        payrun_id: 1,
        payrun_name: "September 2026 Payrun",
        period_start: "2026-09-01",
        period_end: "2026-09-30",
        basic_wage: 75000,
        gross_wage: 78500,
        total_deductions: 6300,
        net_wage: 72200,
        status: "VALIDATED",
      },
    ],
  },

  {
    id: 2,
    first_name: "Marcus",
    last_name: "Johnson",
    email: "marcus.johnson@company.com",
    phone: "+91 87654 32109",
    department: "Engineering",
    job_position: "Backend Engineer",
    manager_id: null,
    manager_name: null,
    schedule_id: 2,
    schedule_name: "Flexible 38h",
    status: "ACTIVE",
    bank_account_no: "ICIC0078901234",
    bank_name: "ICICI Bank",
    ifsc_code: "ICIC0007890",
    tax_id: "BCPMJ5678E",
    joining_date: "2023-06-01",
    avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=100&q=80",
    contracts: [
      {
        id: 102,
        name: "Marcus Johnson / Engineer 2026",
        employee_id: 2,
        start_date: "2026-01-01",
        end_date: null,
        wage: 85000,
        salary_structure_id: 1,
        salary_structure_name: "India Standard Payroll",
        status: "ACTIVE",
      },
    ],
    attendances: [
      {
        id: 1003,
        employee_id: 2,
        date: "2026-09-01",
        check_in: "09:30",
        check_out: "18:30",
        worked_hours: 9,
        overtime_hours: 1,
        status: "OVERTIME",
        notes: null,
      },
    ],
    leave_allocations: [
      {
        id: 203,
        employee_id: 2,
        time_off_type_id: 1,
        time_off_type_name: "Annual Leave",
        time_off_code: "VACATION",
        allocated_days: 21,
        taken_days: 2,
        year: 2026,
      },
    ],
    leave_requests: [],
    payslips: [
      {
        id: 402,
        payrun_id: 1,
        payrun_name: "September 2026 Payrun",
        period_start: "2026-09-01",
        period_end: "2026-09-30",
        basic_wage: 85000,
        gross_wage: 88200,
        total_deductions: 7400,
        net_wage: 80800,
        status: "VALIDATED",
      },
    ],
  },

  {
    id: 3,
    first_name: "Aarav",
    last_name: "Mehta",
    email: "aarav.mehta@company.com",
    phone: "+91 76543 21098",
    department: "Platform Engineering",
    job_position: "Platform Engineer",
    manager_id: null,
    manager_name: null,
    schedule_id: 1,
    schedule_name: "Standard 40h",
    status: "ACTIVE",
    bank_account_no: "SBI0034567890",
    bank_name: "State Bank of India",
    ifsc_code: "SBIN0003456",
    tax_id: "CDPAM9012F",
    joining_date: "2024-01-10",
    avatar_url: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=100&q=80",
    contracts: [
      {
        id: 103,
        name: "Aarav Mehta / Platform 2026",
        employee_id: 3,
        start_date: "2026-01-01",
        end_date: null,
        wage: 60000,
        salary_structure_id: 1,
        salary_structure_name: "India Standard Payroll",
        status: "ACTIVE",
      },
    ],
    attendances: [
      {
        id: 1004,
        employee_id: 3,
        date: "2026-09-01",
        check_in: "09:05",
        check_out: "20:00",
        worked_hours: 10.9,
        overtime_hours: 2.9,
        status: "OVERTIME",
        notes: "Sprint crunch week",
      },
      {
        id: 1005,
        employee_id: 3,
        date: "2026-09-02",
        check_in: "09:00",
        check_out: "18:00",
        worked_hours: 9,
        overtime_hours: 1,
        status: "OVERTIME",
        notes: null,
      },
    ],
    leave_allocations: [
      {
        id: 204,
        employee_id: 3,
        time_off_type_id: 1,
        time_off_type_name: "Annual Leave",
        time_off_code: "VACATION",
        allocated_days: 21,
        taken_days: 3,
        year: 2026,
      },
      {
        id: 205,
        employee_id: 3,
        time_off_type_id: 3,
        time_off_type_name: "Unpaid Leave",
        time_off_code: "UNPAID",
        allocated_days: 5,
        taken_days: 1,
        year: 2026,
      },
    ],
    leave_requests: [
      {
        id: 302,
        employee_id: 3,
        time_off_type_id: 3,
        time_off_type_name: "Unpaid Leave",
        time_off_code: "UNPAID",
        start_date: "2026-09-15",
        end_date: "2026-09-15",
        days: 1,
        reason: "Personal errand",
        status: "APPROVED",
      },
    ],
    payslips: [
      {
        id: 403,
        payrun_id: 1,
        payrun_name: "September 2026 Payrun",
        period_start: "2026-09-01",
        period_end: "2026-09-30",
        basic_wage: 60000,
        gross_wage: 64200,
        total_deductions: 6700,
        net_wage: 57500,
        status: "COMPUTED",
        warnings: ["1 unpaid day deducted"],
      },
    ],
  },

  {
    id: 4,
    first_name: "Fatima",
    last_name: "Al-Hassan",
    email: "fatima.alhassan@company.com",
    phone: "+91 65432 10987",
    department: "HR Operations",
    job_position: "HR Business Partner",
    manager_id: null,
    manager_name: null,
    schedule_id: 1,
    schedule_name: "Standard 40h",
    status: "ON_LEAVE",
    bank_account_no: "AXIS0056789012",
    bank_name: "Axis Bank",
    ifsc_code: "UTIB0005678",
    tax_id: "EFPFA3456G",
    joining_date: "2021-11-20",
    avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=100&q=80",
    contracts: [
      {
        id: 104,
        name: "Fatima Al-Hassan / HR 2026",
        employee_id: 4,
        start_date: "2026-01-01",
        end_date: null,
        wage: 70000,
        salary_structure_id: 1,
        salary_structure_name: "India Standard Payroll",
        status: "ACTIVE",
      },
    ],
    attendances: [
      {
        id: 1006,
        employee_id: 4,
        date: "2026-08-30",
        check_in: "09:00",
        check_out: "18:00",
        worked_hours: 9,
        overtime_hours: 1,
        status: "NORMAL",
        notes: null,
      },
    ],
    leave_allocations: [
      {
        id: 206,
        employee_id: 4,
        time_off_type_id: 2,
        time_off_type_name: "Sick Leave",
        time_off_code: "SICK",
        allocated_days: 10,
        taken_days: 4,
        year: 2026,
      },
    ],
    leave_requests: [
      {
        id: 303,
        employee_id: 4,
        time_off_type_id: 2,
        time_off_type_name: "Sick Leave",
        time_off_code: "SICK",
        start_date: "2026-09-05",
        end_date: "2026-09-08",
        days: 4,
        reason: "Medical procedure",
        status: "APPROVED",
      },
    ],
    payslips: [
      {
        id: 404,
        payrun_id: 1,
        payrun_name: "September 2026 Payrun",
        period_start: "2026-09-01",
        period_end: "2026-09-30",
        basic_wage: 70000,
        gross_wage: 70000,
        total_deductions: 5600,
        net_wage: 64400,
        status: "DRAFT",
      },
    ],
  },

  {
    id: 5,
    first_name: "Lucas",
    last_name: "Ortega",
    email: "lucas.ortega@company.com",
    phone: "+91 54321 09876",
    department: "Infrastructure",
    job_position: "DevOps Engineer",
    manager_id: null,
    manager_name: null,
    schedule_id: 1,
    schedule_name: "Standard 40h",
    status: "ACTIVE",
    bank_account_no: null,
    bank_name: null,
    ifsc_code: null,
    tax_id: null,
    joining_date: "2025-07-01",
    avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=100&q=80",
    contracts: [
      {
        id: 105,
        name: "Lucas Ortega / DevOps 2026",
        employee_id: 5,
        start_date: "2025-07-01",
        end_date: null,
        wage: 55000,
        salary_structure_id: 1,
        salary_structure_name: "India Standard Payroll",
        status: "ACTIVE",
      },
    ],
    attendances: [
      {
        id: 1007,
        employee_id: 5,
        date: "2026-09-01",
        check_in: "09:00",
        check_out: "17:30",
        worked_hours: 8.5,
        overtime_hours: 0.5,
        status: "OVERTIME",
        notes: null,
      },
    ],
    leave_allocations: [
      {
        id: 207,
        employee_id: 5,
        time_off_type_id: 1,
        time_off_type_name: "Annual Leave",
        time_off_code: "VACATION",
        allocated_days: 12,
        taken_days: 0,
        year: 2026,
      },
    ],
    leave_requests: [],
    payslips: [
      {
        id: 405,
        payrun_id: 1,
        payrun_name: "September 2026 Payrun",
        period_start: "2026-09-01",
        period_end: "2026-09-30",
        basic_wage: 55000,
        gross_wage: 55900,
        total_deductions: 4500,
        net_wage: 51400,
        status: "DRAFT",
        warnings: ["Missing bank account", "Missing Tax ID — payrun blocked"],
      },
    ],
  },
];

export default initialEmployees;
